// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57iTavqjjkLBe2mZjHAIgEDvgC_8MBtY',
    appId: '1:738245793547:web:3d8dcccd4ac8a7d016340e',
    messagingSenderId: '738245793547',
    projectId: 'quiz-app-86e6b',
    authDomain: 'quiz-app-86e6b.firebaseapp.com',
    storageBucket: 'quiz-app-86e6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZwR_fINF8bLAZyiXc1P23U6cJnrIB_gU',
    appId: '1:738245793547:android:ed9061a8dcd8e50016340e',
    messagingSenderId: '738245793547',
    projectId: 'quiz-app-86e6b',
    storageBucket: 'quiz-app-86e6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlz9R3qz7-3acJOSSHpPa20arPEwvkc5o',
    appId: '1:738245793547:ios:49640283f853ec9316340e',
    messagingSenderId: '738245793547',
    projectId: 'quiz-app-86e6b',
    storageBucket: 'quiz-app-86e6b.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );
}
